x-common-db: &common-db
  image: mysql:8.0
  restart: always
  environment:
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  volumes:
    - db_data:/var/lib/mysql

services:
  app-dev:
    image: gradle:8.9.0-jdk21
    container_name: app
    working_dir: /app
    command: bash -c "gradle bootRun --continuous --no-daemon"
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    profiles: [ "dev" ]
    volumes:
      - ./:/app
    depends_on:
      - db-dev

  db-dev:
    <<: *common-db
    container_name: db
    profiles: [ "dev" ]
    env_file:
      - .env.dev
    ports:
      - "3307:3306"

volumes:
  db_data:
