version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: jobboard_db
    environment:
      MYSQL_DATABASE: jobboard
      MYSQL_USER: app
      MYSQL_PASSWORD: app_pw
      MYSQL_ROOT_PASSWORD: root_pw
    ports:
      - "3306:3306"   # change left side to 3307 if 3306 is busy
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro  # auto-runs .sql on first start
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot_pw || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: jobboard_adminer
    ports:
      - "8081:8080"   # open http://localhost:8081
    depends_on:
      - db

  importer:
    build: ./importer
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default

  backend:
    build: ./Backend/JobBoardBackend
    container_name: jobboard_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jobboard
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app_pw
      SPRING_SQL_INIT_MODE: never
    ports:
      - "8080:8080"

volumes:
  db_data:
    