# --- DataSource ---
spring.datasource.url=SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/jobboard
spring.datasource.username=root
spring.datasource.password=root_pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- SQL init ---
spring.sql.init.mode=never

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Hibernate Search  ---
spring.jpa.properties.hibernate.search.backend.type=lucene
spring.jpa.properties.hibernate.search.backend.directory.type=local-heap
spring.jpa.properties.hibernate.search.backend.analysis.configurer=bean:customAnalysisConfigurer


# If/when you want a persistent on-disk index (e.g., prod), switch to:
# spring.jpa.properties.hibernate.search.backend.directory.type=local-filesystem
# spring.jpa.properties.hibernate.search.backend.directory.root=./var/lucene-index
logging.level.org.hibernate.search=DEBUG
logging.level.org.hibernate.search.mapper.orm=DEBUG
logging.level.org.hibernate.search.engine=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# --- Server ---
server.port=8080